# Generated by Django 4.2.6 on 2023-10-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=255, unique=True, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
