# Generated by Django 4.2.6 on 2023-10-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_auth', models.CharField(max_length=255, unique=True, verbose_name='Авторизация по телефону')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.IntegerField()),
                ('floor', models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол'), ('no', 'Не указано')], default='no', max_length=25, verbose_name='Пол')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
