# Generated by Django 4.2.6 on 2023-10-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='children_have',
            field=models.CharField(default=1, max_length=100, verbose_name='Имеет ли детей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='family_status',
            field=models.CharField(choices=[('male', 'Холост(не женат)'), ('female', 'Холостая(не замужем)')], default=1, max_length=100, verbose_name='Семейное положение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('male', 'Кыргыз тили'), ('female', 'Русский язык')], default=1, max_length=100, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.BooleanField(default=True, verbose_name='Имеет ли домашних животных'),
        ),
        migrations.AddField(
            model_name='profile',
            name='place_of_living',
            field=models.CharField(default=1, max_length=100, verbose_name='Место проживание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='social_status',
            field=models.CharField(default=1, max_length=100, verbose_name='Социальное положение'),
            preserve_default=False,
        ),
    ]
